# config/packages/monolog.yaml
monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            # log to var/log/(environment).log
            # path: "%kernel.logs_dir%/%kernel.environment%.log"
            path: "/var/log/YOUR PATH HERE /php.log"
            # log *all* messages (debug is lowest level)
            level: info

        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: info